[plugin]
repository = "https://github.com/RajahOmen/BisBuddy.git"
commit = "c96a360090f0817c02ef379b9673e03c44526536"
owners = ["RajahOmen"]
project_path = "BisBuddy"
changelog = """\
**Added**
 - DEBUG: added several tools to expose internals to aid in debugging
 - Added logging to several actions that might lead to crashing
**Fixes**
 - Fixed many issues of bad game data access that may have led to crashes
"""
