[plugin]
repository = "https://github.com/RajahOmen/BisBuddy.git"
commit = "aef49ae19bca5b584d2aaebcf4b70e7b970e6749"
owners = ["RajahOmen"]
project_path = "BisBuddy"
changelog = """\
**Added**
 - DEBUG: added several tools to expose internals to aid in debugging
 - Added logging to several actions that might lead to crashing
 - Add copying/pasting of hex values inside color pickers
**Fixes**
 - Fixed many issues of bad game data access that may have led to crashes
 - Fix bug where prerequisite options show multiple versions of the same shop exchange
 - Fix visual issues with materia on newly imported gearpieces
"""
