[plugin]
repository = "https://github.com/RajahOmen/BisBuddy.git"
commit = "323ff0f8af0e93b833ffb2981ba4ce624fd6abf6"
owners = ["RajahOmen"]
project_path = "BisBuddy"
changelog = """\
**Added**
 - DEBUG: added several tools to expose internals to aid in debugging
 - Added logging to several actions that might lead to crashing
**Fixes**
 - Fixed many issues of bad game data access that may have led to crashes
"""
